// Generated by CoffeeScript 1.6.2
(function() {
  var Badge, BadgeView, Badges;

  window.onerror = function(message, url, lineNumber) {
    var msg;

    msg = "An Error Occured on this page.\nError: " + message + "\nUrl: " + url + "\nLine: " + lineNumber;
    return console.log(msg);
  };

  /*--------------------------------------------------
  coderwall badges
  */


  Badge = Backbone.Model.extend({});

  Badges = Backbone.Collection.extend({
    model: Badge,
    url: function(uname) {
      return "http://coderwall.com/:USERNAME.json?callback=?".replace(":USERNAME", uname);
    },
    fetch: function(uname) {
      var self;

      self = this;
      return $.getJSON(self.url(uname), function(data) {
        console.log(data);
        return self.reset(data["data"]["badges"]);
      });
    }
  });

  BadgeView = Backbone.View.extend({
    el: '#coderwallbadges',
    initialize: function() {
      var self;

      self = this;
      _.bindAll(self, "render");
      self.collection = new Badges();
      self.collection.on("reset", self.render);
      return self.collection.fetch(self.$el.attr("data-source"));
    },
    render: function() {
      var self;

      self = this;
      return self.collection.each(function(badge, i) {
        var badgeImg, description, div;

        div = document.createElement("div");
        div.className = "badge floatLeft";
        div.id = "badge_" + i;
        badgeImg = new Image();
        badgeImg.src = badge.get("badge");
        badgeImg.alt = badge.get("name");
        description = document.createElement("div");
        description.innerHTML = badge.get("description");
        description.className = "tooltip display-none";
        div.appendChild(badgeImg);
        div.appendChild(description);
        $(div).on("mouseover", function() {
          return $("div", this).removeClass("display-none");
        });
        $(div).on("mouseout", function() {
          return $("div", this).addClass("display-none");
        });
        return self.$el.append(div);
      });
    }
  });

  $(function() {
    return new BadgeView();
  });

}).call(this);
